#!/bin/sh

> .env
printf "PG_DB=%s\n"                 "$1" >> .env
printf "PG_USER=%s\n"               "$2" >> .env
printf "PG_PASSWORD=%s\n"           "$3" >> .env

printf "VK_CONFIRMATION_TOKEN=%s\n" "$4" >> .env
printf "VK_API_TOKEN=%s\n"          "$5" >> .env
printf "STATISTIC_TOKEN=%s\n"       "$6" >> .env

printf "WEEK_TYPE=%u\n"             "$7" >> .env
printf "ADMIN_VK_ID=%s\n"           "$8" >> .env

printf "DB_USER_TAG=%s\n"           "$9" >> .env

printf "FLASK_ROUTE_PATH=%s\n"      "${10}" >> .env

printf "DB_USER_TAG=%s\n"           "${11}" >> .env

printf "TZ=%s\n"                    "Europe/Moscow" >> .env

docker-compose up
