version: '3'
services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - PGTZ=${TZ}
      - TZ=${TZ}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    ports:
      - 5432:5432

  api_server:
    image: api_server
    build:
      context: api_server
      args:
        - TZ=${TZ}
    volumes:
      - ./api_server:/api
      - ./api_server/socket:/api/socket
    depends_on:
      - database

  vk_bot:
    image: vk_bot
    build:
      context: vk_bot
      args:
        - TZ=${TZ}
    volumes:
      - ./vk_bot:/bot
      - ./vk_bot/socket:/bot/socket
    depends_on:
      - database

  autoposting:
    image: autoposting
    build:
      context: autoposting
      args:
        - TZ=${TZ}
    volumes:
      - ./autoposting/app:/app
    depends_on:
      - database

  nginx:
    image: nginx:1.13-alpine
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vk_bot/socket:/usr/src/bot_socket:ro
      - ./api_server/socket:/usr/src/api_socket:ro
    depends_on:
      - api_server
      - vk_bot
    ports:
      - 80:80