version: '3'
services:
  api_server:
    image: api_server
    build:
      context: api_server
    volumes:
      - ./api_server:/api
      - ./api_server/socket:/api/socket

  vk_bot:
    image: vk_bot
    build:
      context: vk_bot
    volumes:
      - ./vk_bot:/bot
      - ./vk_bot/socket:/bot/socket

  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vk_bot/socket:/usr/src/bot_socket:ro
      - ./api_server/socket:/usr/src/api_socket:ro
    depends_on:
      - api_server
      - vk_bot
    ports:
      - 80:80