version: '3'
services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - PGTZ=${TZ}
      - TZ=${TZ}
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    ports:
      - 5432:5432

  api_server:
    image: api_server
    environment:
      - DB_NAME=${PG_DB}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_HOST=database
      - TZ=${TZ}
    build:
      context: api_server
    volumes:
      - ./api_server:/api
      - ./api_server/socket:/api/socket
    depends_on:
      - database

  vk_bot:
    image: vk_bot
    environment:
      - DB_NAME=${PG_DB}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_HOST=database
      - FLASK_ROUTE_PATH=${FLASK_ROUTE_PATH}
      - VK_CONFIRMATION_TOKEN=${VK_CONFIRMATION_TOKEN}
      - VK_API_TOKEN=${VK_API_TOKEN}
      - STATISTIC_TOKEN=${STATISTIC_TOKEN}
      - WEEK_TYPE=${WEEK_TYPE}
      - ADMIN_VK_ID=${ADMIN_VK_ID}
      = DB_USER_TAG=${DB_USER_TAG}
      = FLASK_ROUTE_PATH=${FLASK_ROUTE_PATH}
      - TZ=${TZ}
    build:
      context: vk_bot
    volumes:
      - ./vk_bot:/bot
      - ./vk_bot/socket:/bot/socket
    depends_on:
      - database

  autoposting:
    image: autoposting
    environment:
      - DB_NAME=${PG_DB}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_HOST=database
      - VK_API_TOKEN=${VK_API_TOKEN}
      - STATISTIC_TOKEN=${STATISTIC_TOKEN}
      - WEEK_TYPE=${WEEK_TYPE}
      - ADMIN_VK_ID=${ADMIN_VK_ID}
      = DB_USER_TAG=${DB_USER_TAG}
      - TZ=${TZ}
    build:
      context: autoposting
    volumes:
      - ./autoposting/app:/app
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vk_bot/socket:/usr/src/bot_socket:ro
      - ./api_server/socket:/usr/src/api_socket:ro
    depends_on:
      - api_server
      - vk_bot
    ports:
      - 80:80
