version: '3'
services:
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  api_server:
    image: api_server
    build:
      context: api_server
    volumes:
      - ./api_server:/api
      - ./api_server/socket:/api/socket
    depends_on:
      - database
    ports:
      - 5432:5432

  vk_bot:
    image: vk_bot
    build:
      context: vk_bot
    volumes:
      - ./vk_bot:/bot
      - ./vk_bot/socket:/bot/socket
    depends_on:
      - database
    ports:
      - 5432:5432

  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vk_bot/socket:/usr/src/bot_socket:ro
      - ./api_server/socket:/usr/src/api_socket:ro
    depends_on:
      - api_server
      - vk_bot
    ports:
      - 80:80