#!/bin/sh

printf "\[%s\]"                      "bot" > config.cfg

printf "DB_NAME=%s\n"                "$1" >> config.cfg
printf "DB_USER=%s\n"                "$2" >> config.cfg
printf "DB_PASSWORD=%s\n"            "$3" >> config.cfg
printf "DB_HOST=%s\n"                "$4" >> config.cfg

printf "TOKEN=%s\n"                  "$5" >> config.cfg

printf "WEEK_TYPE=%u\n"              "$6" >> config.cfg
printf "STATISTIC_TOKEN=%s\n"        "$7" >> config.cfg
printf "ADMIN_VK_ID=%s\n"            "$8" >> config.cfg

printf "LOG_DIR_PATH=%s\n"           "./" >> config.cfg

cp /usr/share/zoneinfo/$9 /etc/localtime && echo $9 > /etc/timezone

python3 auto_posting_thread.py