#!/bin/sh

> config.cfg
printf "DB_NAME='%s'\n"              "$1" >> config.cfg
printf "DB_USER='%s'\n"              "$2" >> config.cfg
printf "DB_PASSWORD='%s'\n"          "$3" >> config.cfg
printf "DB_HOST='%s'\n"              "$4" >> config.cfg

printf "CONFIRMATION_TOKEN='%s'\n"   "$5" >> config.cfg
printf "TOKEN='%s'\n"                "$6" >> config.cfg

printf "WEEK_TYPE=%u\n"              "$7" >> config.cfg
printf "STATISTIC_TOKEN='%s'\n"      "$8" >> config.cfg
printf "ADMIN_VK_ID='%s'\n"          "$9" >> config.cfg

printf "DB_USER_TAG='%s'\n"          "${10}" >> config.cfg

printf "FLASK_ROUTE_PATH='%s'\n"     "${11}" >> config.cfg

printf "VK_ID_BLACKLIST='%s'\n"      "${12}" >> config.cfg

printf "LOG_DIR_PATH='%s'\n"         "/bot/log/" >> config.cfg

cp config.cfg app/config.cfg
rm config.cfg

cp /usr/share/zoneinfo/${13} /etc/localtime && echo ${13} > /etc/timezone

gunicorn app:app --workers 4 -b  unix:/bot/socket/bot.sock